baseURL = "https://danielcardoza.com"
title = "Daniel Cardoza"
#themesDir = "../.."
theme = "m10c"
paginate = 10

[params]
  author = "Daniel Cardoza"
  description = "Software engineer, fitness enthusiast, Canadian."
  avatar = "images/avatar.png"
  [[params.social]]
    name = "github"
    url = "https://github.com/dang3r"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/_dancards"
  [[params.social]]
    name = "github"
    url = "//github.com/dang3r"

  [[params.social]]
    name = "linkedin"
    url = "//linkedin.com/in/dcardoza"
  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"